server:
  port: 8085

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      discovery:
        locator:
          enable: true
      routes:



        - id: ms-bus-service
          uri: lb://ms-bus-service
          predicates:
            - Path=/api/buses/**, /api/conductores/**
#          filters:
#            - AuthFilter


        - id: ms-route-service
          uri: lb://ms-route-service
          predicates:
            - Path=/api/rutas/**
#          filters:
#            - AuthFilter

        - id: ms-history-service
          uri: lb://ms-history-service
          predicates:
            - Path=/api/recorridos/**
#          filters:
#              - AuthFilter


        - id: ms-notification-service
          uri: lb://ms-notification-service
          predicates:
            - Path=/api/notificaciones/**, /ws/notificaciones/**
#          filters:
#              - AuthFilter


        - id: ms-tracking-service
          uri: lb://ms-tracking-service
          predicates:
            - Path=/api/tracking/**, /ws/tracking/**
#          filters:
#              - AuthFilter


        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**






